spring:
  datasource:
    url: jdbc:mysql://db:3306/clientes_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: maddytec@123

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true

  jackson:
    default-property-inclusion: NON_NULL

jwt:
  secret: _M@d50n@r@uj0d@51lv@_
  # Token com duracao em minutos
  expiration: 30

server:
  error:
    include-message: always
